firefly_iii_app: 
  image: jc5x/firefly-iii:latest
  depends_on:
    - firefly_iii_db
  ports: 
    - "9005:80"
  env_file: ./services/firefly/firefly.env
  volumes: 
    - 
      source: firefly_iii_export
      target: /var/www/firefly-iii/storage/export
      type: volume
    - 
      source: firefly_iii_upload
      target: /var/www/firefly-iii/storage/upload
      type: volume
firefly_iii_db: 
  image: "postgres:10"
  environment:
    - POSTGRES_PASSWORD=secret_firefly_password
    - POSTGRES_USER=firefly
  volumes: 
    - firefly_iii_db:/var/lib/postgresql/data

volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~